services:
  postgres:
    image: postgres:9.6
    volumes:
      - /opt/tmp/learn_phoenix_13:/var/lib/postgresql/data
    environment:
      # The password we'll use to access the databases:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
    ports:
      - "5432:5432"
  